### ISSUE TITLE
Uploaded files in different folders cannot have same name

### ISSUE THREAD

**Issue by fydrah** [ObjectifLibre/sendfilestome#1]
Hi,

# Description
`sendfilestome` reports an internal server error if you upload 2 files with the same name even if they are in a separated folder.

# How to reproduce
* create 2 folders
* upload `file.txt` in folder1
* upload `file.txt` in folder2

--> Server Error (500)

**Comment by gpocentek** [comment]
The 500 return code is another bug (fixed).

But there is indeed a mixup with files with the same name in different folders.
